# Generated by Django 4.1.2 on 2022-10-19 15:58
from django.contrib.postgres.operations import CITextExtension
import apps.users.models.user
from django.conf import settings
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=250, verbose_name='first name')),
                ('last_name', models.CharField(max_length=250, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=250, verbose_name='phone number')),
                ('second_phone_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='second phone number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', apps.users.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='profile image')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, verbose_name='gender')),
                ('postal_code', models.IntegerField(verbose_name='postal code')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=100)], verbose_name='description')),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('work_application', models.CharField(max_length=250, verbose_name='work application')),
                ('experience', models.CharField(blank=True, max_length=250, null=True, verbose_name='experience')),
                ('weekly_days', models.IntegerField(verbose_name='weekly days')),
                ('daily_hours', models.FloatField(blank=True, null=True, verbose_name='daily hours')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='instagram url')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='facebook url')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Caregiver profile',
                'verbose_name_plural': 'Caregiver profiles',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='profile image')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, verbose_name='gender')),
                ('postal_code', models.IntegerField(verbose_name='postal code')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=100)], verbose_name='description')),
                ('beneficiary_person', models.CharField(max_length=250, verbose_name='beneficiary person')),
                ('helping_period', models.CharField(max_length=250, verbose_name='helping period')),
                ('weekly_days', models.IntegerField(verbose_name='weekly days')),
                ('daily_hours', models.FloatField(verbose_name='daily hours')),
                ('care_type', models.CharField(max_length=250, verbose_name='care type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Beneficiary profile',
                'verbose_name_plural': 'Beneficiary profiles',
            },
        ),
    ]
