# Generated by Django 4.1.2 on 2022-10-15 09:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='profile image')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=100)], verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=250, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='second phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='BeneficiaryProfile',
            fields=[
                ('abstractprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.abstractprofile')),
                ('beneficiary_person', models.CharField(max_length=250, verbose_name='beneficiary person')),
                ('helping_period', models.CharField(max_length=250, verbose_name='helping period')),
                ('weekly_days', models.IntegerField(verbose_name='weekly days')),
                ('daily_hours', models.IntegerField(verbose_name='daily hours')),
                ('care_type', models.CharField(max_length=250, verbose_name='care type')),
            ],
            options={
                'verbose_name': 'Beneficiary profile',
                'verbose_name_plural': 'Beneficiary profiles',
            },
            bases=('users.abstractprofile',),
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('abstractprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.abstractprofile')),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('work_application', models.CharField(max_length=250, verbose_name='work application')),
                ('experience', models.CharField(blank=True, max_length=250, null=True, verbose_name='experience')),
                ('weekly_days', models.IntegerField(verbose_name='weekly days')),
                ('daily_hours', models.FloatField(blank=True, null=True, verbose_name='daily hours')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='instagram url')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='facebook url')),
            ],
            options={
                'verbose_name': 'Caregiver profile',
                'verbose_name_plural': 'Caregiver profiles',
            },
            bases=('users.abstractprofile',),
        ),
        migrations.AddField(
            model_name='abstractprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
