# Generated by Django 4.1.2 on 2022-10-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_beneficiaryprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaryprofile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='caregiverprofile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='beneficiaryprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='gender'),
        ),
    ]
