# Generated by Django 4.1.2 on 2022-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_beneficiaryprofile_weekly_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin URL'),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='twitter URL'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook URL'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='instagram URL'),
        ),
    ]
