# Generated by Django 4.1.2 on 2022-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_caregiverprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_password_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='requested password reset at'),
        ),
    ]
