# Generated by Django 4.1.2 on 2022-11-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_requested_password_reset_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requested_password_reset_at',
        ),
    ]
