from apps.users.views.register_beneficiary_api_view import RegisterBeneficiaryAPIView
from apps.users.views.register_caregiver_api_view import RegisterCaregiverAPIView
from apps.users.views.regiser_api_view import RegisterAPIView
