from apps.users.views.beneficiary_details_api_view import BeneficiaryDetailsAPIView
from apps.users.views.beneficiary_list_api_view import BeneficiaryListAPIView
from apps.users.views.caregiver_details_api_view import CaregiverDetailsAPIView
from apps.users.views.caregiver_list_api_view import CaregiverListAPIView
from apps.users.views.login_api_view import LoginAPIView
from apps.users.views.logout_api_view import LogoutAPIView
from apps.users.views.register_beneficiary_api_view import RegisterBeneficiaryAPIView
from apps.users.views.register_caregiver_api_view import RegisterCaregiverAPIView
