export const caregiverFormFields = [
  //General information
  [
    { id: "first_name", type: "text", name: "first_name", label: "Ime", placeholder: "Unesite Vaše ime*" },
    { id: "last_name", type: "text", name: "last_name", label: "Prezime", placeholder: "Unesite Vaše prezime*" },
    { id: "email", type: "email", name: "email", label: "E-mail", placeholder: "Unesite Vaš E-mail*" },
    {
      id: "phone_number",
      type: "text",
      name: "phone_number",
      label: "Broj telefona",
      placeholder: "Unesite Vaš primarni broj telefona*",
    },
    {
      id: "second_phone_number",
      type: "text",
      name: "second_phone_number",
      label: "Broj telefona 2",
      placeholder: "Unesite Vaš rezervni broj telefona",
    },
    { id: "password", type: "password", name: "password", label: "Lozinka", placeholder: "Unesite Vašu lozinku*" },
    {
      id: "postal_code",
      type: "number",
      name: "postal_code",
      label: "Poštanski broj",
      placeholder: "Poštanski broj*",
    },
    {
      id: "city",
      type: "dropdown",
      name: "city",
      label: "Mesto stanovanja",
      placeholder: "Mesto stanovanja*",
      options: {},
    },
    {
      id: "birthdate",
      type: "datepicker",
      name: "birthdate",
      label: "Datum rođenja",
      placeholder: "Dan / Mesec / Godina rodjenja*",
    },
    {
      id: "gender",
      type: "dropdown",
      name: "gender",
      label: "Pol",
      placeholder: "Pol*",
      options: { male: "muški", female: "ženski" },
    },
  ],
  //Caregiver fields
  [
    {
      id: "work_application",
      type: "text",
      name: "work_application",
      label: "Profesija",
      placeholder: "Profesija*",
    },
    { id: "experience", type: "text", name: "experience", label: "Iskustvo", placeholder: "Iskustvo*" },
    {
      id: "weekly_days",
      type: "text",
      name: "weekly_days",
      label: "Dostupnost tokom nedelje",
      placeholder: "Dostupnost tokom nedelje*",
    },
    {
      id: "daily_hours",
      type: "number",
      name: "daily_hours",
      step: ".01",
      label: "Koliko sati ste dostupni?",
      placeholder: "Koliko sati dnevno*",
    },
    {
      id: "facebook_url",
      type: "text",
      name: "facebook_url",
      label: "Facebook profil link",
      placeholder: "Link do vašeg facebook profila*",
      optional: true,
    },
    {
      id: "instagram_url",
      type: "text",
      name: "instagram_url",
      label: "Instagram profil link",
      placeholder: "Link do vašeg instagram profila*",
      optional: true,
    },
  ],
];
