# Generated by Django 4.1.2 on 2022-10-19 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='subtitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/donations/donation', verbose_name='cover image')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=100)], verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('payment_purpose', models.CharField(max_length=250, verbose_name='payment purpose')),
                ('payment_receiver', models.CharField(max_length=250, verbose_name='payment receiver')),
                ('payment_code', models.IntegerField(verbose_name='payment code')),
                ('payment_bank_account', models.CharField(max_length=20, verbose_name='payment bank account')),
                ('payment_model', models.IntegerField(blank=True, null=True, verbose_name='payment model')),
                ('payment_reference_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='payment reference number')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='donations.donation', verbose_name='donation')),
            ],
            options={
                'verbose_name': 'Financial info',
                'verbose_name_plural': 'Financial info',
            },
        ),
        migrations.CreateModel(
            name='DonationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/donations/donation_company', verbose_name='company image')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=100)], verbose_name='description')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='donations.donation', verbose_name='donation')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
