# Generated by Django 4.1.2 on 2022-10-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationcompany',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='financialdonation',
            options={'verbose_name': 'Financial donation', 'verbose_name_plural': 'Financial donations'},
        ),
        migrations.RemoveField(
            model_name='financialdonation',
            name='payment_reference_model',
        ),
        migrations.AddField(
            model_name='financialdonation',
            name='payment_reference_number',
            field=models.CharField(default='', max_length=20, verbose_name='payment reference number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationcompany',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.donation', verbose_name='donation'),
        ),
        migrations.AlterField(
            model_name='financialdonation',
            name='payment_bank_account',
            field=models.CharField(max_length=20, verbose_name='payment bank account'),
        ),
    ]
