# Generated by Django 4.1.2 on 2022-10-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialinfo',
            options={'verbose_name': 'Financial Info', 'verbose_name_plural': 'Financial Info'},
        ),
    ]
