# Generated by Django 4.1.2 on 2022-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_financialinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcompany',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin URL'),
        ),
        migrations.AddField(
            model_name='donationcompany',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='twitter URL'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(null=True, upload_to='images/donations', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='donationcompany',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook URL'),
        ),
        migrations.AlterField(
            model_name='donationcompany',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='instagram URL'),
        ),
    ]
