# Generated by Django 4.1.2 on 2022-10-15 17:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donationcompany_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('payment_purpose', models.CharField(max_length=250, verbose_name='payment purpose')),
                ('payment_receiver', models.CharField(max_length=250, verbose_name='payment receiver')),
                ('payment_code', models.IntegerField(verbose_name='payment code')),
                ('payment_bank_account', models.CharField(max_length=20, verbose_name='payment bank account')),
                ('payment_model', models.IntegerField(verbose_name='payment model')),
                ('payment_reference_number', models.CharField(max_length=20, verbose_name='payment reference number')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.donation', verbose_name='donation')),
            ],
            options={
                'verbose_name': 'Financial info',
                'verbose_name_plural': 'Financial info',
            },
        ),
        migrations.DeleteModel(
            name='FinancialDonation',
        ),
    ]
