# Generated by Django 4.1.2 on 2022-10-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_financialinfo_delete_financialdonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcompany',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='donationcompany',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='donations.donation', verbose_name='donation'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='payment_model',
            field=models.IntegerField(blank=True, null=True, verbose_name='payment model'),
        ),
        migrations.AlterField(
            model_name='financialinfo',
            name='payment_reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='payment reference number'),
        ),
    ]
