# Generated by Django 4.1.2 on 2022-10-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donationcompany_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcompany',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='donations.donation', verbose_name='donation'),
        ),
    ]
