# Generated by Django 4.1.2 on 2022-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogcategory_blog_blogcategory_blogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blogs.blogcategory', verbose_name='categories'),
        ),
    ]
