# Generated by Django 4.1.2 on 2022-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogauthor_linkedin_url_blogauthor_twitter_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='image',
            field=models.ImageField(upload_to='images/blogs/authors', verbose_name='image'),
        ),
    ]
