# Generated by Django 4.1.2 on 2022-10-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blogcategory_blogs_blog_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blogs.blog', verbose_name='blog'),
        ),
    ]
