# Generated by Django 4.1.2 on 2022-10-16 16:33

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogsection_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blogs.blog', verbose_name='blog'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='image',
            field=models.ImageField(upload_to='images/blogAuthors', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=[('#F87024', 'orange'), ('#0075FF', 'blue'), ('#229EBD', 'light green-blue')], verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=100, verbose_name='media type'),
        ),
    ]
