# Generated by Django 4.1.2 on 2022-11-26 13:31

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subject', models.CharField(max_length=250, verbose_name='subject')),
                ('recipient_email', models.CharField(max_length=250, verbose_name='recipient email')),
                ('email_context', models.JSONField(default=dict, verbose_name='email context')),
                ('template_path', models.CharField(max_length=250, verbose_name='template path')),
                ('group', models.CharField(default='general', max_length=250, verbose_name='group')),
                ('status', models.CharField(choices=[('pending', 'waiting to send email'), ('success', 'successfully sent email'), ('failure', 'failed to send email')], default='pending', help_text='Note that the email can successfully be sent even if the recipient email address does not exist', max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Email Thread',
                'verbose_name_plural': 'Email Threads',
            },
        ),
    ]
