# Generated by Django 4.1.2 on 2022-12-04 15:33

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('image', models.ImageField(upload_to='images/common/organization_partner', verbose_name='logo image')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Organization Partner',
                'verbose_name_plural': 'Organization Partners',
            },
        ),
    ]
