from apps.users.viewsets.abstract_profile_viewset import AbstractProfileViewSet
from apps.users.viewsets.beneficiary_profile_viewset import BeneficiaryProfileViewSet
from apps.users.viewsets.caregiver_profile_viewset import CaregiverProfileViewSet
