export const beneficiaryEditList = [
  {
    title: "IME",
    fieldName: "first_name",
    type: "text",
    placeholder: "Vaše ime*",
  },
  {
    title: "PREZIME",
    fieldName: "last_name",
    type: "text",
    placeholder: "Vaše prezime*",
  },
  {
    title: "OPŠTE INFORMACIJE",
    fieldname: "description",
    type: "textArea",
    width: "full",
    styleClass: "textArea",
    placeholder: "Unesite kratak opis*",
  },
  {
    title: "BROJ TELEFONA",
    fieldName: "phone_number",
    type: "text",
    placeholder: "Vaš primarni broj telefona*",
  },
  {
    title: "BROJ TELEFONA 2",
    fieldName: "second_phone_number",
    type: "text",
    placeholder: "Vaš rezervni broj telefona",
  },
  {
    title: "EMAIL",
    fieldName: "email",
    type: "text",
    placeholder: "Vaša e-mail adresa*",
  },
  {
    title: "KOME JE POTREBNA NEGA?",
    fieldName: "beneficiary_person",
    type: "text",
    placeholder: "Kome je potrebna nega?*",
  },
  {
    title: "VRSTA POMOĆI",
    fieldName: "care_type",
    type: "text",
    placeholder: "Vrsta potrebne pomomoći*",
  },
  {
    title: "PERIOD PRUŽANJA POMOĆI",
    fieldName: "helping_period",
    type: "text",
    placeholder: "Period pružanja pomomoći*",
  },
  {
    title: "BROJ DANA NEDELJNO",
    fieldName: "weekly_days",
    type: "text",
    placeholder: "Koliko dana nedeljno?*",
  },
  {
    title: "SATI NEDELJNO",
    fieldName: "daily_hours",
    type: "text",
    placeholder: "Koliko sati dnevno? (0-24h)*",
  },
];
